# Generated by Django 5.1.6 on 2026-04-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                    ("HOD", "HOD"),
                ],
                db_index=True,
                default="STUDENT",

                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RoleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("FACULTY", "Faculty"),
                            ("HOD", "HOD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_requests",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]