# Generated by Django 5.1.6 on 2026-04-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_upload_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_editable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
