export const MOCK_USER = {
  id: 1,
  email: "test@example.com",
  username: "testuser",
  first_name: "Test",
  last_name: "User",
  role: "student",
  avatar: null,
  bio: "A test user generated by the mock API.",
  is_verified: true,
};

export const MOCK_TOKEN = "mock_jwt_token_1234567890";
