# Generated by Django 5.1.6 on 2026-04-24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_unit"),
        ("exams", "0004_examtemplate_exampaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampaper",
            name="title",
            field=models.CharField(default="Question Paper Draft", max_length=255),
        ),
        migrations.AddField(
            model_name="exampaper",
            name="subject_ref",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_exam_papers", to="academics.subject"),
        ),
        migrations.AddField(
            model_name="exampaper",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
