# Generated by Django 5.1.6 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_note_created_by_alter_note_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_type",
            field=models.CharField(default="Lecture", max_length=50),
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["note_type"], name="idx_note_type"),
        ),
    ]
