# Generated by Django 5.1.6 on 2026-04-24

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_material_options_alter_subject_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("title", models.CharField(max_length=255)),
                ("order_index", models.PositiveIntegerField(db_index=True, default=1)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="academics.subject")),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["subject__name", "order_index", "title"],
            },
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(fields=("subject", "order_index"), name="uniq_unit_subject_order"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["subject", "order_index"], name="idx_unit_subject_order"),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(fields=["subject", "title"], name="idx_unit_subject_title"),
        ),
    ]
