export const ROUTE_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  FILE_MANAGER: "/file-manager",
  FILE_PREVIEW: "/file-preview/:fileId",
  ACTIVITY_FEED: "/activity-feed",
  ONLINE_TEST: "/online-test/:examId",
  STUDENT_ONLINE_TEST_LEGACY: "/student/online-test/:examId",

  STUDENT_BASE: "/student",
  STUDENT_DASHBOARD: "/student/dashboard",
  STUDENT_STUDY_OVERVIEW: "/student/study-overview",
  STUDENT_ANALYTICS: "/student/analytics",
  STUDENT_PROJECT_SUBMISSION: "/student/project-submission",
  STUDENT_NOTES: "/student/notes",
  STUDENT_NOTES_VIEW: "/student/notes/view/:noteId",
  STUDENT_NOTES_SUBJECT: "/student/notes/:subjectId",
  STUDENT_AI: "/student/ai",
  STUDENT_AI_SAVED_NOTES: "/student/ai/saved-notes",
  STUDENT_AI_GENERATED: "/student/ai/generated",
  STUDENT_AI_GENERATED_NOTE: "/student/ai/generated/:noteId",

  SYSTEM_DASHBOARD: "/system/dashboard",

  TEACHER_DASHBOARD: "/teacher/dashboard",
  TEACHER_CLASSES: "/teacher/classes",
  TEACHER_ACTIVITY: "/teacher/activity",
  TEACHER_NOTES_STUDIO: "/teacher/notes-studio",
  TEACHER_SAVED_NOTES: "/teacher/saved-notes",
  TEACHER_EXPLORE_NOTES: "/teacher/explore-notes",
  TEACHER_QUESTION_PAPER: "/teacher/question-paper",
  TEACHER_MATERIALS_UPLOAD: "/teacher/materials-upload",
  TEACHER_TEMPLATE_BUILDER: "/teacher/question-paper/template-builder",
  TEACHER_TEMPLATE_PREVIEW: "/teacher/question-paper/template-preview",
  TEACHER_QUESTION_GENERATOR: "/teacher/question-generator",
  TEACHER_EXAM_PREVIEW: "/teacher/question-paper/exam-preview",
  TEACHER_EXAM_EXPORT: "/teacher/question-paper/exam-export",
  TEACHER_ONLINE_TESTS: "/teacher/online-tests",
  TEACHER_ONLINE_TEST_RESULTS: "/teacher/online-test-results/:examId",

  HOD_DASHBOARD: "/hod/dashboard",
  HOD_PERFORMANCE: "/hod/performance",
  HOD_TEACHER_CONTRIBUTIONS: "/hod/teacher-contributions",
  HOD_MATERIAL_APPROVAL: "/hod/material-approval",
  HOD_STUDENT_ENGAGEMENT: "/hod/student-engagement",
  HOD_PROJECT_APPROVALS: "/hod/project-approvals",
  HOD_STUDENT_ANALYTICS: "/hod/student-analytics",

  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_USERS: "/admin/users",
  ADMIN_ACTIVITY_LOGS: "/admin/activity-logs",
  ADMIN_STORAGE: "/admin/storage",
  ADMIN_AI_USAGE: "/admin/ai-usage",
  ADMIN_STUDENT_ANALYTICS: "/admin/student-analytics",
};

export const buildPath = {
  filePreview: (fileId) => `/file-preview/${fileId}`,
  onlineTest: (examId) => `/online-test/${examId}`,
  studentNotesSubject: (subjectId) => `/student/notes/${subjectId}`,
  studentNoteViewer: (noteId) => `/student/notes/view/${noteId}`,
  studentAiGeneratedNote: (noteId) => `/student/ai/generated/${noteId}`,
  teacherOnlineTestResults: (examId) => `/teacher/online-test-results/${examId}`,
};
