export const ROUTE_PATHS = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  CHOOSE_ROLE: "/choose-role",
  DASHBOARD: "/dashboard",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  FILE_MANAGER: "/file-manager",
  FILE_PREVIEW: "/file-preview/:fileId",
  ACTIVITY_FEED: "/activity-feed",
  SYSTEM_DASHBOARD: "/system/dashboard",
};
