import axios from 'axios';

// The real API is commented out since the backend is currently unbuilt/unreachable
/*
const api = axios.create({
  baseURL: '/api/auth',
  headers: {
    'Content-Type': 'application/json',
  },
});
*/

// Mock Data for frontend development
const MOCK_USER = {
  id: 1,
  email: 'test@example.com',
  username: 'testuser',
  first_name: 'Test',
  last_name: 'User',
  role: 'student',
  avatar: null,
  bio: 'A test user generated by the mock API.',
  is_verified: true,
};

const MOCK_TOKEN = 'mock_jwt_token_1234567890';

// Simulates network delay
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export const authAPI = {
  login: async (credentials) => {
    await delay(1000); // 1s simulation
    console.log('[MOCK API] Login attempt with:', credentials);
    
    // Simulate generic successful login regardless of credentials
    return {
      user: { ...MOCK_USER, email: credentials.email },
      access: MOCK_TOKEN,
      refresh: 'mock_refresh_token'
    };
  },
  
  register: async (userData) => {
    await delay(1200); // 1.2s simulation
    console.log('[MOCK API] Register attempt with:', userData);
    
    // Simulate generic successful registration
    return {
      user: {
        ...MOCK_USER,
        email: userData.email,
        username: userData.username,
        first_name: userData.first_name,
        last_name: userData.last_name,
      },
      access: MOCK_TOKEN,
      refresh: 'mock_refresh_token'
    };
  },
  
  forgotPassword: async (emailData) => {
    await delay(800);
    console.log('[MOCK API] Forgot password request for:', emailData);
    return { message: 'Password reset email sent if the account exists.' };
  },
};
