# Generated by Django 5.1.6 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_studymaterialbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studymaterial",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
